name: "Hello Actions"
description: "LOL"
author: "raymondbayat@gmail.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Ray"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
