name: Ray's job toggels
on:
  workflow_dispatch:
jobs:
  build:
    name: Ray
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Ray"
 
